POST http://localhost:4000/employee-api/employees
Content-Type: application/json   

{
    "Name":"emp3",
    "Email":"emp3@mail.com",
    "Mobile":"1234567890",
    "Designation":"member",
    "Company":"xyz"
}

###

GET http://localhost:4000/employee-api/employees

###

PUT http://localhost:4000/employee-api/employees/emp2@mail.com
Content-Type: application/json   

{
    "Name":"emp2",
    "Email":"emp2@mail.com",
    "Mobile":"1234567890",
    "Designation":"member",
    "Company":"xyz"
}

###

DELETE http://localhost:4000/employee-api/employees/emp3@mail.com
